sudo: false
language: go
go:
  - 1.7.x
  - 1.8.x
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
install:
  - # This is needed to prevent default install action "go get -t -v ./..."
script:
  - diff -u <(echo -n) <(gofmt -d ./apl ./tests)
  - go tool vet ./apl ./tests
  - go test -v -race ./apl